#ifndef SRC_TRANSLATING_CALCULATING_CALCULATION_ERROR_CODES_H_
#define SRC_TRANSLATING_CALCULATING_CALCULATION_ERROR_CODES_H_


enum calculation_error_codes {
    C_SUCCESS = 0,
    C_ZERO_DIVISION_ERROR = 1,
    C_EMPTY_STACK_ERROR = 2,
    C_INVALID_REVERSE_POLISH_NOTATION_ERROR = 3,
    C_UNKNOWN_ACTION_ERROR = 4,
    C_NEGATIVE_ARGUMENT_FOR_LOGARITHM_ERROR = 5,
    C_NEGATIVE_ARGUMENT_FOR_SQRT_ERROR = 6
};


#endif  //  SRC_TRANSLATING_CALCULATING_CALCULATION_ERROR_CODES_H_