#ifndef SRC_TRANSLATING_CALCULATING_CALCULATION_ERROR_CODES_H_
#define SRC_TRANSLATING_CALCULATING_CALCULATION_ERROR_CODES_H_


enum calculation_error_codes {
    C_SUCCESS = 0,
    C_ZERO_DIVISION_ERROR = 1,
    C_EMPTY_STACK_ERROR = 2,
    C_INVALID_REVERSE_POLISH_NOTATION_ERROR = 3,
    C_UNKNOWN_ACTION_ERROR = 4,
    C_NEGATIVE_ARGUMENT_FOR_LOGARITHM_ERROR = 5,
    C_NEGATIVE_ARGUMENT_FOR_SQRT_ERROR = 6,
    C_NEGATIVE_BASE_FOR_REAL_EXPONENT_ERROR = 7,
    C_NEGATIVE_EXPONENT_FOR_ZERO_BASE_ERROR = 8
};

static const double sg_failed_result_for_calculating_rpn = -1.0;

#endif  //  SRC_TRANSLATING_CALCULATING_CALCULATION_ERROR_CODES_H_