#ifndef SRC_PARSING_EXPRESSION_EXPRESSION_CHECK_CODES_H_
#define SRC_PARSING_EXPRESSION_EXPRESSION_CHECK_CODES_H_


enum expression_check_error_codes {
    EC_EXPRESSION_IS_INCORRECT = -1,
    EC_EXPRESSION_IS_CORRECT   = 0
};


#endif  //  SRC_PARSING_EXPRESSION_EXPRESSION_CHECK_CODES_H_