#ifndef SRC_PARSING_EXPRESSION_STRING_TO_NUMBER_ERROR_CODES_H_
#define SRC_PARSING_EXPRESSION_STRING_TO_NUMBER_ERROR_CODES_H_

enum conversion_status_codes {
    CS_SUCCESSFUL_CONVERSION = 0,
    CS_FAILED_CONVERSION = 1
};

#endif //  SRC_PARSING_EXPRESSION_STRING_TO_NUMBER_ERROR_CODES_H_