CC=gcc
CFLAGS=-Wall -Werror -Wextra -std=c11 -c


SOURCE_DIRECTORIES=data_structures field translating_calculating drawing parsing_expression

BUILD_DIRECTORY=../build

TARGET=$(BUILD_DIRECTORY)/graph.exe
TARGET_TEST=$(BUILD_DIRECTORY)/graph_test.exe


OBJECT_MAIN=$(BUILD_DIRECTORY)/graph.o
OBJECT_MAIN_TEST=$(BUILD_DIRECTORY)/graph_test.o



SOURCE_FILES_ALL=$(foreach directory_as_variable, $(SOURCE_DIRECTORIES),$(wildcard $(directory_as_variable)/*.c))
SOURCE_FILES=$(filter-out %_test.c, $(SOURCE_FILES_ALL))
SOURCE_FILES_TESTS=$(filter %_test.c, $(SOURCE_FILES_ALL))



OBJECT_FILES_ALL_IN_SOURCE_DIRECTORIES=$(patsubst %.c,%.o,$(SOURCE_FILES_ALL))
OBJECT_FILES_ALL_IN_BUILD_DIRECTORIES=$(addprefix $(BUILD_DIRECTORY)/,$(OBJECT_FILES_ALL_IN_SOURCE_DIRECTORIES))


OBJECT_FILES_TESTS_IN_SOURCE_DIRECTORIES=$(patsubst %.c,%.o,$(SOURCE_FILES_TESTS))
OBJECT_FILES_TESTS_IN_BUILD_DIRECTORIES=$(addprefix $(BUILD_DIRECTORY)/,$(OBJECT_FILES_TESTS_IN_SOURCE_DIRECTORIES))


OBJECT_FILES_IN_SOURCE_DIRECTORIES=$(patsubst %.c,%.o,$(SOURCE_FILES))
OBJECT_FILES_IN_BUILD_DIRECTORIES=$(addprefix $(BUILD_DIRECTORY)/,$(OBJECT_FILES_IN_SOURCE_DIRECTORIES))


DEPENDENCY_DIRECTORY=../dependencies
DEPENDENCY_FILES_ALL_IN_SOURCE_DIRECTORIES=$(patsubst %.c,%.d,$(SOURCE_FILES_ALL))
DEPENDENCY_FILES_ALL_IN_DEPENDENCY_DIRECTORIES=$(addprefix $(DEPENDENCY_DIRECTORY)/,$(DEPENDENCY_FILES_ALL_IN_SOURCE_DIRECTORIES))
DEPENDENCY_FILES_ALL_IN_DEPENDENCY_DIRECTORIES+=$(DEPENDENCY_DIRECTORY)/graph.d

DEPENDENCY_DIRECTORIES=$(dir $(DEPENDENCY_FILES_ALL_IN_DEPENDENCY_DIRECTORIES))

DEPFLAGS=-MT $@ -MMD -MP -MF $(DEPENDENCY_DIRECTORY)/$*.d
DEPFLAGS_MAIN= -MT $@ -MMD -MP -MF

all: $(TARGET)


test: $(TARGET_TEST)


compile: $(OBJECT_FILES_IN_BUILD_DIRECTORIES)


compile_test: $(OBJECT_FILES_TESTS_IN_BUILD_DIRECTORIES)


$(OBJECT_MAIN): graph.c $(DEPENDENCY_DIRECTORY)/graph.d | $(DEPENDENCY_DIRECTORY)
		mkdir -p $(DEPENDENCY_DIRECTORY)/$(dir $*)
		$(CC) $(CFLAGS) -o $@ $< $(DEPFLAGS_MAIN) $(DEPENDENCY_DIRECTORY)/graph.d


$(OBJECT_MAIN_TEST): graph.c $(DEPENDENCY_DIRECTORY)/graph.d | $(DEPENDENCY_DIRECTORY)
		mkdir -p $(DEPENDENCY_DIRECTORY)/$(dir $*)
		$(CC) $(CFLAGS) -o $@ $< -D TEST_GRAPH_ $(DEPFLAGS_MAIN) $(DEPENDENCY_DIRECTORY)/graph.d

# $(OBJECT_MAIN_TEST): graph.c  drawing/drawing.h


$(TARGET): $(OBJECT_FILES_IN_BUILD_DIRECTORIES) $(OBJECT_MAIN)
		$(CC) -o $@ $^


$(TARGET_TEST): $(OBJECT_FILES_IN_BUILD_DIRECTORIES) $(OBJECT_MAIN_TEST) $(OBJECT_FILES_TESTS_IN_BUILD_DIRECTORIES) 
		$(CC) -o $@ $^


$(OBJECT_FILES_ALL_IN_BUILD_DIRECTORIES): $(BUILD_DIRECTORY)/%.o: %.c $(DEPENDENCY_DIRECTORY)/%.d | $(DEPENDENCY_DIRECTORY)
		mkdir -p $(dir $@)
		mkdir -p $(DEPENDENCY_DIRECTORY)/$(dir $*)
		$(CC) $(CFLAGS) $< -o $@ $(DEPFLAGS)


$(DEPENDENCY_DIRECTORY):
		mkdir -p $(DEPENDENCY_DIRECTORY)


$(DEPENDENCY_FILES_ALL_IN_DEPENDENCY_DIRECTORIES):


clean: 
		rm -rf $(BUILD_DIRECTORY)/* $(DEPENDENCY_DIRECTORY)/*


print:
		foreach directory_as_variable, $(DEPENDENCY_FILES_ALL_IN_DEPENDENCY_DIRECTORIES), echo $(dir, $(directory_as_variable))


include $(wildcard $(DEPENDENCY_FILES_ALL_IN_DEPENDENCY_DIRECTORIES))