CC=gcc
CFLAGS=-Wall -Werror -Wextra -std=c11 -c


SOURCE_DIRECTORIES=data_structures field translating_calculating drawing parsing_expression

BUILD_DIRECTORY=../build

TARGET=$(BUILD_DIRECTORY)/graph.exe
TARGET_TEST=$(BUILD_DIRECTORY)/graph_test.exe


OBJECT_MAIN=$(BUILD_DIRECTORY)/graph.o
OBJECT_MAIN_TEST=$(BUILD_DIRECTORY)/graph_test.o



SOURCE_FILES_ALL=$(foreach directory_as_variable, $(SOURCE_DIRECTORIES),$(wildcard $(directory_as_variable)/*.c))
SOURCE_FILES=$(filter-out %_test.c, $(SOURCE_FILES_ALL))
SOURCE_FILES_TESTS=$(filter %_test.c, $(SOURCE_FILES_ALL))



OBJECT_FILES_ALL_IN_SOURCE_DIRECTORIES=$(patsubst %.c,%.o,$(SOURCE_FILES_ALL))
OBJECT_FILES_ALL_IN_BUILD_DIRECTORIES=$(addprefix $(BUILD_DIRECTORY)/,$(OBJECT_FILES_ALL_IN_SOURCE_DIRECTORIES))


OBJECT_FILES_TESTS_IN_SOURCE_DIRECTORIES=$(patsubst %.c,%.o,$(SOURCE_FILES_TESTS))
OBJECT_FILES_TESTS_IN_BUILD_DIRECTORIES=$(addprefix $(BUILD_DIRECTORY)/,$(OBJECT_FILES_TESTS_IN_SOURCE_DIRECTORIES))


OBJECT_FILES_IN_SOURCE_DIRECTORIES=$(patsubst %.c,%.o,$(SOURCE_FILES))
OBJECT_FILES_IN_BUILD_DIRECTORIES=$(addprefix $(BUILD_DIRECTORY)/,$(OBJECT_FILES_IN_SOURCE_DIRECTORIES))



all: $(TARGET)


test: $(TARGET_TEST)


compile: $(OBJECT_FILES_IN_BUILD_DIRECTORIES)


compile_test: $(OBJECT_FILES_TESTS_IN_BUILD_DIRECTORIES)


$(OBJECT_MAIN): graph.c
		$(CC) $(CFLAGS) -o $@ $^


$(OBJECT_MAIN_TEST): graph.c
		$(CC) $(CFLAGS) -o $@ $^ -D TEST_GRAPH_



$(TARGET): $(OBJECT_FILES_IN_BUILD_DIRECTORIES) $(OBJECT_MAIN)
		$(CC) -o $@ $^


$(TARGET_TEST): $(OBJECT_FILES_IN_BUILD_DIRECTORIES) $(OBJECT_MAIN_TEST) $(OBJECT_FILES_TESTS_IN_BUILD_DIRECTORIES) 
		$(CC) -o $@ $^


$(OBJECT_FILES_ALL_IN_BUILD_DIRECTORIES): $(BUILD_DIRECTORY)/%.o: %.c
		mkdir -p $(dir $@)
		$(CC) $(CFLAGS) $< -o $@


clean: 
		rm -rf $(BUILD_DIRECTORY)/*

